openapi: 3.0.0
info:
  title: Inventory Management API
  version: 1.0.0
  description: API docs for product module

servers:
  - url: http://localhost:5000


security:
  - bearerAuth: []

paths:
  /api/product/add:
    post:
      summary: Add a new product
      tags:
        - Products
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        '200':
          description: Product added successfully

  /api/product:
    get:
      summary: Get all products
      tags:
        - Products
      responses:
        '200':
          description: List of all products

  /api/product/{id}:
    get:
      summary: Get product by ID
      tags:
        - Products
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Product fetched

    put:
      summary: Update product by ID
      tags:
        - Products
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        '200':
          description: Product updated

    delete:
      summary: Delete product by ID
      tags:
        - Products
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Product deleted

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Product:
      type: object
      required:
        - productName
        - category
        - supplier
        - price
        - stock
      properties:
        productName:
          type: string
          example: Sugar
        productDescription:
          type: string
          example: Used for cooking
        category:
          type: string
          example: 665e4e2f3a9ad4bbd3f6b212
        supplier:
          type: string
          example: 665e4e5d3a9ad4bbd3f6b213
        price:
          type: number
          example: 50
        stock:
          type: number
          example: 100

