openapi: 3.0.0
info:
  title: Inventory Management API - Suppliers
  version: 1.0.0
  description: API documentation for managing suppliers

servers:
  - url: http://localhost:5000

security:
  - bearerAuth: []

paths:
  /api/supplier/add:
    post:
      summary: Add a new supplier
      tags:
        - Supplier
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                phone:
                  type: string
              required:
                - name
      responses:
        '201':
          description: Supplier created successfully
        '400':
          description: Invalid input
        '500':
          description: Server error

  /api/supplier:
    get:
      summary: Get all suppliers
      tags:
        - Supplier
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of suppliers
        '500':
          description: Server error

  /api/supplier/{id}:
    get:
      summary: Get supplier by ID
      tags:
        - Supplier
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Supplier details
        '404':
          description: Supplier not found
        '500':
          description: Server error

    put:
      summary: Update a supplier
      tags:
        - Supplier
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                phone:
                  type: string
              required:
                - name
      responses:
        '200':
          description: Supplier updated
        '404':
          description: Supplier not found
        '500':
          description: Server error

    delete:
      summary: Delete a supplier
      tags:
        - Supplier
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Supplier deleted
        '404':
          description: Supplier not found
        '500':
          description: Server error

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
