openapi: 3.0.0
info:
  title: Inventory Management API
  version: 1.0.0
  description: API docs for category module

servers:
  - url: http://localhost:5000

security:
  - bearerAuth: []

paths:
  /api/category/add:
    post:
      summary: Add a new category
      tags:
        - Category
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
              required:
                - name
      responses:
        '201':
          description: Category created successfully
        '400':
          description: Invalid input
        '500':
          description: Server error

  /api/category:
    get:
      summary: Get all categories
      tags:
        - Category
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of categories
        '500':
          description: Server error

  /api/category/{id}:
    get:
      summary: Get category by ID
      tags:
        - Category
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Category details
        '404':
          description: Category not found
        '500':
          description: Server error

    put:
      summary: Update a category
      tags:
        - Category
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
              required:
                - name
      responses:
        '200':
          description: Category updated
        '404':
          description: Category not found
        '500':
          description: Server error

    delete:
      summary: Delete a category
      tags:
        - Category
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Category deleted
        '404':
          description: Category not found
        '500':
          description: Server error

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
