openapi: 3.0.0
info:
  title: Inventory Management API - User
  version: 1.0.0
  description: API documentation for User module (Register, Login, Profile)

servers:
  - url: http://localhost:5000

security:
  - bearerAuth: []

paths:


  /api/auth/login:
    post:
      summary: Login user
      tags:
        - User
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
                - email
                - password
      responses:
        '200':
          description: Login successful, returns token
        '401':
          description: Invalid credentials
        '500':
          description: Server error

 

  /api/users:
    get:
      summary: Get all users (admin only)
      tags:
        - User
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of all users
        '403':
          description: Forbidden (not admin)
        '500':
          description: Server error

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
